# -*- coding: utf-8 -*-
"""task1_bert_musiccaps (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nv3tHjCdadeiNjCqtWI8hrHshfAm2Ap9
"""

!pip install -q transformers datasets torch scikit-learn matplotlib pandas

import ast
import random
from collections import Counter

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

raw = load_dataset("google/MusicCaps")
print(raw)

df = raw["train"].to_pandas()
print("Rows:", len(df))
print("Columns:", list(df.columns))
df[["caption", "aspect_list"]].head()

def parse_aspects(aspect_str):
    try:
        aspects = ast.literal_eval(aspect_str)
    except (ValueError, SyntaxError):
        aspects = [a.strip() for a in str(aspect_str).split(",")]
    return [a.strip().lower() for a in aspects if a.strip()]


df["aspects"] = df["aspect_list"].apply(parse_aspects)
df[["caption", "aspects"]].head()

TOP_K = 50

tag_counter = Counter()
for aspects in df["aspects"]:
    tag_counter.update(aspects)

top_tags = [tag for tag, _ in tag_counter.most_common(TOP_K)]
tag_to_idx = {tag: i for i, tag in enumerate(top_tags)}

print(f"Top {TOP_K} tags:")
for tag, count in tag_counter.most_common(TOP_K):
    print(f"  {tag:35s} {count}")

"""## 3. Build multi-label target vectors"""

def build_label_vector(aspects, tag_to_idx):
    vec = np.zeros(len(tag_to_idx), dtype=np.float32)
    for a in aspects:
        if a in tag_to_idx:
            vec[tag_to_idx[a]] = 1.0
    return vec

df["labels"] = df["aspects"].apply(lambda a: build_label_vector(a, tag_to_idx))


df = df[df["caption"].str.len() > 0].reset_index(drop=True)
print("Final dataset size:", len(df))

has_label = df["labels"].apply(lambda v: v.sum() > 0).mean()
print(f"Fraction of clips with >=1 of the top-{TOP_K} tags: {has_label:.2%}")
print(f"Average tags-per-clip (within top-{TOP_K}): {df['labels'].apply(lambda v: v.sum()).mean():.2f}")

train_df, temp_df = train_test_split(df, test_size=0.3, random_state=SEED)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=SEED)

print(f"Train: {len(train_df)}   Val: {len(val_df)}   Test: {len(test_df)}")

MODEL_NAME = "distilbert-base-uncased"
MAX_LEN = 128
BATCH_SIZE = 16

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)


class MusicTagDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len=128):
        self.captions = dataframe["caption"].tolist()
        self.labels = np.stack(dataframe["labels"].values)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.captions)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.captions[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt",
        )
        item = {"input_ids": enc["input_ids"].squeeze(0),
                "attention_mask": enc["attention_mask"].squeeze(0)}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.float32)
        return item


train_ds = MusicTagDataset(train_df, tokenizer, MAX_LEN)
val_ds = MusicTagDataset(val_df, tokenizer, MAX_LEN)
test_ds = MusicTagDataset(test_df, tokenizer, MAX_LEN)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE)

print(f"Batches -> train: {len(train_loader)}  val: {len(val_loader)}  test: {len(test_loader)}")

class BERTTagClassifier(nn.Module):
    """Task 1 model from the project spec:
    t = BERT_CLS(X_text);  y_hat_k = sigmoid(w_k^T t + b_k)
    """

    def __init__(self, model_name, num_labels, dropout=0.1):
        super().__init__()
        self.bert = AutoModel.from_pretrained(model_name, attn_implementation="eager")
        hidden_size = self.bert.config.hidden_size
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(hidden_size, num_labels)

    def forward(self, input_ids, attention_mask, output_attentions=False):
        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_attentions=output_attentions,
        )
        cls_repr = outputs.last_hidden_state[:, 0, :]
        logits = self.classifier(self.dropout(cls_repr))
        if output_attentions:
            return logits, outputs.attentions
        return logits


model = BERTTagClassifier(MODEL_NAME, num_labels=TOP_K).to(device)
sum(p.numel() for p in model.parameters() if p.requires_grad)

EPOCHS = 5
LR = 2e-5

optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer, num_warmup_steps=int(0.1 * total_steps), num_training_steps=total_steps
)
criterion = nn.BCEWithLogitsLoss()


def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    total_loss = 0.0
    all_preds, all_labels = [], []

    for batch in loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        if train:
            optimizer.zero_grad()
            logits = model(input_ids, attention_mask)
            loss = criterion(logits, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
        else:
            with torch.no_grad():
                logits = model(input_ids, attention_mask)
                loss = criterion(logits, labels)

        total_loss += loss.item() * input_ids.size(0)
        preds = (torch.sigmoid(logits) > 0.5).float().detach().cpu().numpy()
        all_preds.append(preds)
        all_labels.append(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    all_preds = np.concatenate(all_preds, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    macro_f1 = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    micro_f1 = f1_score(all_labels, all_preds, average="micro", zero_division=0)
    return avg_loss, macro_f1, micro_f1


history = {"train_loss": [], "val_loss": [],
           "train_macro_f1": [], "val_macro_f1": [],
           "train_micro_f1": [], "val_micro_f1": []}

for epoch in range(1, EPOCHS + 1):
    train_loss, train_macro, train_micro = run_epoch(train_loader, train=True)
    val_loss, val_macro, val_micro = run_epoch(val_loader, train=False)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["train_macro_f1"].append(train_macro)
    history["val_macro_f1"].append(val_macro)
    history["train_micro_f1"].append(train_micro)
    history["val_micro_f1"].append(val_micro)

    print(f"Epoch {epoch}/{EPOCHS} | "
          f"train_loss={train_loss:.4f} val_loss={val_loss:.4f} | "
          f"train_macroF1={train_macro:.4f} val_macroF1={val_macro:.4f} | "
          f"train_microF1={train_micro:.4f} val_microF1={val_micro:.4f}")

epochs_range = range(1, EPOCHS + 1)

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

axes[0].plot(epochs_range, history["train_macro_f1"], marker="o", label="Train Macro-F1")
axes[0].plot(epochs_range, history["val_macro_f1"], marker="o", label="Val Macro-F1")
axes[0].set_title("Macro-F1 vs Epoch")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Macro-F1")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(epochs_range, history["train_micro_f1"], marker="o", label="Train Micro-F1")
axes[1].plot(epochs_range, history["val_micro_f1"], marker="o", label="Val Micro-F1")
axes[1].set_title("Micro-F1 vs Epoch")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Micro-F1")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("task1_f1_curves.png", dpi=150)
plt.show()

test_loss, test_macro, test_micro = run_epoch(test_loader, train=False)
print(f"TEST  | loss={test_loss:.4f}  Macro-F1={test_macro:.4f}  Micro-F1={test_micro:.4f}")

model.eval()
sample_df = test_df.sample(n=5, random_state=SEED).reset_index(drop=True)

for i, row in sample_df.iterrows():
    enc = tokenizer(row["caption"], truncation=True, padding="max_length",
                     max_length=MAX_LEN, return_tensors="pt")
    enc = {k: v.to(device) for k, v in enc.items()}
    with torch.no_grad():
        logits = model(enc["input_ids"], enc["attention_mask"])
        probs = torch.sigmoid(logits).cpu().numpy()[0]

    top5_idx = probs.argsort()[::-1][:5]
    predicted_tags = [(top_tags[j], round(float(probs[j]), 3)) for j in top5_idx]
    true_tags = [top_tags[j] for j in range(TOP_K) if row["labels"][j] == 1.0]

    print(f"\nExample {i + 1}")
    print("Caption:", row["caption"][:200], "...")
    print("Ground-truth top-tags present:", true_tags if true_tags else "(none in top-50)")
    print("Top-5 predicted tags:", predicted_tags)

example_caption = sample_df.iloc[0]["caption"]
enc = tokenizer(example_caption, truncation=True, max_length=MAX_LEN, return_tensors="pt")
enc = {k: v.to(device) for k, v in enc.items()}

model.eval()
with torch.no_grad():
    _, attentions = model(enc["input_ids"], enc["attention_mask"], output_attentions=True)


last_layer_attn = attentions[-1][0]
cls_attn = last_layer_attn[:, 0, :].mean(0).cpu().numpy()
tokens = tokenizer.convert_ids_to_tokens(enc["input_ids"][0])

plt.figure(figsize=(max(8, len(tokens) * 0.35), 3))
plt.bar(range(len(tokens)), cls_attn)
plt.xticks(range(len(tokens)), tokens, rotation=90)
plt.title("Last-layer [CLS] attention (averaged over heads)")
plt.ylabel("Attention weight")
plt.tight_layout()
plt.savefig("task1_attention_example.png", dpi=150)
plt.show()

torch.save(model.state_dict(), "task1_bert_temp.pt")

model = BERTTagClassifier(MODEL_NAME, num_labels=TOP_K).to(device)
model.load_state_dict(torch.load("task1_bert_temp.pt"))

import json as json_lib

torch.save(model.state_dict(), "task1_bert_tag_classifier.pt")
with open("task1_top_tags.json", "w") as f:
    json_lib.dump(top_tags, f, indent=2)

print("Saved model weights to task1_bert_tag_classifier.pt")
print("Saved tag vocabulary (top-{} tags) to task1_top_tags.json".format(TOP_K))

from google.colab import drive
drive.mount('/content/drive')


!mkdir -p "/content/drive/MyDrive/CSE425_Project"

!cp task1_bert_tag_classifier.pt "/content/drive/MyDrive/CSE425_Project/"
!cp task1_top_tags.json "/content/drive/MyDrive/CSE425_Project/"

print("Done! Files are now safely saved in your Google Drive.")